level = "easy"
name = "rum_thirst"
tags = [ "dp", "algo", "collections",]
time_to_solve_sec = 250
description_en = "A pirate walks along a deck lined with barrels of rum. Each barrel contains a certain number of liters (given as an array of non‑negative integers). The pirate cannot take rum from two adjacent barrels (that would make noise). What is the maximum total amount of rum he can drink unnoticed?\n"
description_ru = "Пират идет по палубе, заставленной бочками с ромом. В каждой бочке разное количество литров (задано массивом неотрицательных целых чисел). Он не может брать ром из двух соседних бочек (поднимется шум). Какое максимальное количество рома он может выпить незаметно?\n"
limits = "- $0 \\leq \\text{len}(\\text{barrels}) \\leq 1000$\n- $0 \\leq \\text{barrels}[i] \\leq 1000$\n"
solution = "def solution(barrels: list[int]) -> int:\n    prev2 = prev1 = 0\n    for x in barrels:\n        prev2, prev1 = prev1, max(prev1, prev2 + x)\n    return prev1\n"
examples = "solution([]) == 0\nsolution([5]) == 5\nsolution([5, 3]) == 5\nsolution([5, 3, 7]) == 12\nsolution([2, 7, 9, 3, 1]) == 12\n"
[[input_signature]]
argument_name = "barrels"

[input_signature.type]
name = "array"
[input_signature.type.nested]
name = "integer"
[[asserts]]
arguments = [ [],]
comment = "Test 1"
expected = 0

[[asserts]]
arguments = [ [ 5,],]
comment = "Test 2"
expected = 5

[[asserts]]
arguments = [ [ 5, 3,],]
comment = "Test 3"
expected = 5

[[asserts]]
arguments = [ [ 5, 3, 7,],]
comment = "Test 4"
expected = 12

[[asserts]]
arguments = [ [ 2, 7, 9, 3, 1,],]
comment = "Test 5"
expected = 12

[[asserts]]
arguments = [ [ 1, 2, 3, 4, 5,],]
comment = "Test 6"
expected = 9

[[asserts]]
arguments = [ [ 10, 0, 10, 0, 10,],]
comment = "Test 7"
expected = 30

[[asserts]]
arguments = [ [ 100, 200, 300,],]
comment = "Test 8"
expected = 400

[[asserts]]
arguments = [ [ 137, 582, 867,],]
comment = "Test 9"
expected = 1004

[[asserts]]
arguments = [ [ 978, 883,],]
comment = "Test 10"
expected = 978

[[asserts]]
arguments = [ [ 243,],]
comment = "Test 11"
expected = 243

[[asserts]]
arguments = [ [ 241, 310, 105, 738, 405, 490, 158, 92, 68, 20, 411, 562, 939, 296, 819, 783, 60, 227,],]
comment = "Test 12"
expected = 4026

[[asserts]]
arguments = [ [ 637, 261, 759, 367, 814, 707, 965, 861, 757, 667, 944, 542, 29, 860, 476, 794,],]
comment = "Test 13"
expected = 6530

[[asserts]]
arguments = [ [ 812, 587, 841, 82, 496, 780, 267,],]
comment = "Test 14"
expected = 2433

[[asserts]]
arguments = [ [ 331,],]
comment = "Test 15"
expected = 331

[[asserts]]
arguments = [ [ 232, 379, 985, 384,],]
comment = "Test 16"
expected = 1217

[[asserts]]
arguments = [ [ 474, 627, 382, 273,],]
comment = "Test 17"
expected = 900

[[asserts]]
arguments = [ [ 585, 33, 439, 494,],]
comment = "Test 18"
expected = 1079

[[asserts]]
arguments = [ [ 463, 886, 573, 877, 946, 799, 476, 462, 520, 875, 601, 194, 189, 823, 524, 487, 644, 628,],]
comment = "Test 19"
expected = 6031

[[asserts]]
arguments = [ [ 485, 275, 673, 541, 682,],]
comment = "Test 20"
expected = 1840

[[asserts]]
arguments = [ [ 265, 297, 701, 931, 700, 821, 869, 911, 190, 667, 236,],]
comment = "Test 21"
expected = 3627

[[asserts]]
arguments = [ [ 109, 630, 719, 773,],]
comment = "Test 22"
expected = 1403

[[asserts]]
arguments = [ [ 988, 213, 11, 533, 753, 37, 161, 934, 244, 17, 56, 900, 824, 697, 150, 877, 711, 376, 245, 119,],]
comment = "Test 23"
expected = 5672

[[asserts]]
arguments = [ [ 370, 480, 492, 291, 426, 232, 457, 5, 419, 874,],]
comment = "Test 24"
expected = 2619

[[asserts]]
arguments = [ [ 534, 424, 826, 310, 983, 374, 296, 178,],]
comment = "Test 25"
expected = 2639

[[asserts]]
arguments = [ [ 185, 125, 677, 459, 342, 245, 202, 974, 501, 643, 505, 187, 491, 302, 469, 908, 270,],]
comment = "Test 26"
expected = 4220

[[asserts]]
arguments = [ [ 693, 44, 803, 916, 532, 123,],]
comment = "Test 27"
expected = 2028

[[asserts]]
arguments = [ [ 927, 740, 702, 805, 784, 901, 926, 154, 266, 690, 650, 869, 926, 103, 893, 335,],]
comment = "Test 28"
expected = 6074

[[asserts]]
arguments = [ [ 168, 428, 706, 428, 650, 288, 490, 863, 221, 811, 486, 827, 986, 524, 187, 517, 540, 241,],]
comment = "Test 29"
expected = 5307

[[asserts]]
arguments = [ [],]
comment = "Test 30"
expected = 0

[output_signature.type]
name = "integer"
