base_score        = 100
level             = "easy"
name              = "max_divisible_by_30"
tags              = ["math", "greedy"]
time_to_solve_sec = 200

description_en = """
Given an integer $N$ ($0 \\leq N \\leq 10^9$), rearrange its digits to obtain the **maximum** number divisible by $30$.
If impossible, return $-1$.
"""

description_ru = """
Дано целое число $N$ ($0 \\leq N \\leq 10^9$). Переставьте его цифры, чтобы получить **максимальное** число, кратное $30$.
Если это невозможно, верните $-1$.
"""

limits = """
- $0 \\leq N \\leq 10^9$
"""

solution = """
def solution(n: int) -> int:
    s = str(n)
    if '0' not in s or sum(map(int, s)) % 3 != 0:
        return -1
    return int(''.join(sorted(s, reverse=True)))
"""

examples = """
solution(105) == 510
solution(322) == -1
solution(30) == 30
"""

[[input_signature]]
argument_name = "n"
[input_signature.type]
name = "integer"

[output_signature.type]
name = "integer"

[[asserts]]
arguments = [105]
expected  = 510

[[asserts]]
arguments = [322]
expected  = -1

[[asserts]]
arguments = [30]
expected  = 30

[[asserts]]
arguments = [18018]
expected  = 88110

[[asserts]]
arguments = [280587678]
expected  = 888776520

[[asserts]]
arguments = [629804342]
expected  = -1

[[asserts]]
arguments = [903813795]
expected  = 998753310

[[asserts]]
arguments = [2620710]
expected  = 7622100

[[asserts]]
arguments = [709234783]
expected  = -1

[[asserts]]
arguments = [27189840]
expected  = 98874210

[[asserts]]
arguments = [502728939]
expected  = 998753220

[[asserts]]
arguments = [960352987]
expected  = -1

[[asserts]]
arguments = [857407070]
expected  = -1

[[asserts]]
arguments = [775011]
expected  = 775110

[[asserts]]
arguments = [7016518]
expected  = -1

[[asserts]]
arguments = [5814]
expected  = -1

[[asserts]]
arguments = [320012625]
expected  = 653222100

[[asserts]]
arguments = [236767938]
expected  = -1

[[asserts]]
arguments = [890631]
expected  = 986310

[[asserts]]
arguments = [289056]
expected  = 986520

[[asserts]]
arguments = [7033052]
expected  = -1

[[asserts]]
arguments = [208012]
expected  = -1

[[asserts]]
arguments = [607174044]
expected  = 776444100

[[asserts]]
arguments = [2049762]
expected  = 9764220

[[asserts]]
arguments = [567260568]
expected  = 876665520

[[asserts]]
arguments = [46523898]
expected  = -1

[[asserts]]
arguments = [482088]
expected  = 888420

[[asserts]]
arguments = [5079439]
expected  = -1

[[asserts]]
arguments = [70080]
expected  = 87000

[[asserts]]
arguments = [467044410]
expected  = 764444100

[[asserts]]
arguments = [3333]
expected  = -1
